server:
  port: 8081
  tomcat:
    threads:
      max: 400
      min-spare: 20

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro_user_db
    username: root
    password: theboy$G$Kpc2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#        register-health-indicator: true
#        sliding-window-size: 10
#        minimum-number-of-calls: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 5s
#        automatic-transition-from-open-to-half-open-enabled: true
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-type: COUNT_BASED
#        event-consumer-buffer-size: 10

rating:
  service:
    baseUrl: http://RATING-SERVICE
hotel:
  service:
    baseUrl: http://HOTEL-SERVICE



